language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: fDEOY00cKwWB7kMJWKlULUaq00LUkF1PrVWsmmTqNnA0SL8X26jvQiEhLKwmvTNbJ1bzGrTOdpQBbajzxEYxzVO6lUmF1R36UQkjr2eIV5gtbluaZEbmmGn6kuLk9l3qHA/EWzZscIBYXbzK1xphj3Fg4aPM9+3Dwhoevsf+0fhGKuVecsm0kuXFcxu/ZEkHCCv7yaMoS3hH+9WQzsoJ5vJdpgjPvSK/rZjOprOY4wazRzBEUysTCEnIIFNDe07rSWJ9RqaJbbJwwcfwtxritSrztwlHfHHK59/flacPwiSGDmC5CRs6hi9OwWDZ+fo/BNyX72++mr1uBE9h9EnRJdTixohlKKXXstK2wMVK4mb5pqU0hL7ECZyN3l9UKrfpP0/HenpasDXQ/92hSFx95WiPFZMvPvwRuN7EjJ9ZsjxNef+BfqB8YxbHMZgf3magduCZ1YOsMqpxtziS6/Q6cRuFW5zV3LWxBQAiyxcA2/W7FIemwZ0VMi267EOu8KxSCMj7jL4Wp9NAHukHHoD1vUF3+Wujg8zF0ZPAuK0RnMzZPT/s3RM++GJmfyTc1x3Yc9ywme7Z4uoNcVQ004tqDQI/524BDASNXyyUvwMtFZ4AhelXKE6nRoy9hIVSW5xnPK1AlbafspswLFdfJcKk4Mu/tvEFo4xm0l65sejMufk=
  app: evening-bastion-56652
  on:
    repo: maryzhenghan/react-trello-testing
